language: python

# python:
#   - "3.7"

services:
  - docker

# command to install dependencies
# install:
#   - pip install -r requirements.txt
# command to run tests
script:
  - docker build -t python-sample .
  - docker run python-sample /bin/sh -c "make test"
